config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :users, only: [:show]
  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  resources :musics
  root 'musics#index'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/music.rb
class Music < ApplicationRecord
    belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  has_many :musics
  validates :name, presence: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    before_action :configure_permitted_parameters, if: :devise_controller?
    
    protected
    def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
    # アカウント編集の時にnameとprofileのストロングパラメータを追加
    devise_parameter_sanitizer.permit(:account_update, keys: [:name, :like_artist, :unlike_artist])
    end

end

app/controllers/hello_controller.rb
class HelloController < ApplicationController
  def index
    @musics = Music.all
  end
end

app/controllers/musics_controller.rb
class MusicsController < ApplicationController
  before_action :authenticate_user!, only: [:new, :create]
  
  def index
      if params[:search] == nil
        @musics= Music.all
      elsif params[:search] == ''
        @musics= Music.all
      else
        @musics = Music.where("artist_name LIKE ? ",'%' + params[:search] + '%')
      end
  end
  
  def link
  end
  
  def new
    @music = Music.new
  end
  
  def create
    music = Music.new(music_params)
    music.user_id = current_user.id
    if music.save
      redirect_to :action => "index"
    else
      redirect_to :action => "new"
    end
  end
  
  def edit
    @music = Music.find(params[:id])
  end
  
  def update
    music = Music.find(params[:id])
    if music.update(music_params)
      redirect_to :action => "index", :id => music.id
    else
      redirect_to :action => "new"
    end
  end
  
  def destroy
    music = Music.find(params[:id])
    music.destroy
    redirect_to action: :index
  end
  
  private
    def music_params
      params.require(:music).permit(:artist_name,:song_name)
    end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def show
    @user = User.find(params[:id]) 
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/hello_helper.rb
module HelloHelper
end

app/helpers/musics_helper.rb
module MusicsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/hello/index.html.erb
音楽オススメサイト
<%= link_to 'ログイン', :controller => "devise/sessions", :action => "new" %>
<%= link_to '新規登録', :controller => "devise/registrations", :action => "new" %>
<%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<div class="musics-container">
  <% @musics.each do |t| %>
    <div class="music">
      <%= t.artist_name %>
      <%= t.song_name %>
      <%= t.created_at %>
    </div>
  <% end %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AppName</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/musics/edit.html.erb
<h1>音楽オススメサイト</h1>
<h3>編集</h3>
<%= form_for @music do |f| %>
  <div class="field">
    <%= f.label :アーティスト名 %>
    <%= f.text_field :artist_name, :size => 140 %>
    <%= f.label :曲名 %>
    <%= f.text_field :song_name, :size => 140 %>
  </div>
  <%= f.submit "決定" %>
<% end %>
<%= link_to 'トップ', :controller => "musics", :action => "index" %>

app/views/musics/index.html.erb
<h1>音楽オススメサイト</h1>
<% if user_signed_in? %>
  <%= link_to '投稿', :controller => "musics", :action => "new" %>
  <%= link_to "マイページ", user_path(current_user.id) %>　
  <%= button_to 'ログアウト', destroy_user_session_path, method: :delete %>
<% else %>
  <%= link_to 'ログイン', :controller => "devise/sessions", :action => "new" %>
  <%= link_to '新規登録', :controller => "devise/registrations", :action => "new" %>
<% end %>

<h3>投稿を検索</h3>
 <%= form_tag({controller:"musics",action:"index"}, method: :get) do %>
   <%= text_field_tag :search %>
   <%= submit_tag '検索する'  %>
<% end %>

<h3>投稿一覧</h3>
<div class="musics-container">
  <% @musics.each do |t| %>
    <a href="/users/<%= t.user.id %>"><%= t.user.name %></a>
    好きなアーティスト : <%= t.user.like_artist %>
    好きでないアーティスト : <%= t.user.unlike_artist %>
    <div class="music">
      <%= t.artist_name %>
      <%= t.song_name %>
      <%= t.created_at %>
    </div>
  <% end %>
</div>

app/views/musics/new.html.erb
<h1>音楽オススメサイト</h1>
<h3>新規投稿</h3>
<%= form_for @music do |f| %>
  <div class="field">
    <%= f.label :アーティスト名 %>
    <%= f.text_field :artist_name, :size => 140 %>
    <%= f.label :曲名 %>
    <%= f.text_field :song_name, :size => 140 %>
  </div>
  <%= f.submit "投稿" %>
<% end %>
<%= link_to 'トップ', :controller => "musics", :action => "index" %>

app/views/users/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/users/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' && controller_name != 'registrations' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end %>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{OmniAuth::Utils.camelize(provider)}", omniauth_authorize_path(resource_name, provider), method: :post %><br />
  <% end %>
<% end %>

app/views/users/show.html.erb
<h1>音楽オススメサイト</h1>
<h3>プロフィール</h3>
<p>名前 : <%= @user.name %></p>
<p>好きなアーティスト : <%= @user.like_artist %></p>
<p>好きでないアーティスト : <%= @user.unlike_artist %></p>

<% if user_signed_in? %>
 <% if current_user.id == @user.id %>
  <%= link_to "編集する", edit_user_registration_path %>
 <% end %>
<% end %>

<h3>あなたの投稿</h3>
<% @user.musics.each do |t| %>
  アーティスト名：<%= t.artist_name %>
  曲名：<%= t.song_name %>
  <% if user_signed_in? %>
   <% if current_user.id == @user.id %>
    <%= link_to "編集する", edit_music_path(t.id) %>
    <%= button_to "削除する", music_path(t.id), method: :delete %>
   <% end %>
  <% end %>
<% end %>

<%= link_to "トップ", musics_path %>